(part "2454985-3"
    (packageRef "24549853")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "A2") (portType INOUT))
        (port "B1" (symbPinId 3) (portName "B1") (portType INOUT))
        (port "B2" (symbPinId 4) (portName "B2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "2454985-3")
    (property "Arrow_Part_Number" "2454985-3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/2454985-3/te-connectivity?region=nac")
    (property "Description" "DIP & SIP Switches, Switch, Gold Flash, Black Housing, PA9T, Auto-Insertable, 2 Switch, -40  85 C, DIP Switch, Alcoswitch DIP ADE")
    (property "Datasheet_Link" "https://www.mouser.com/datasheet/2/418/3/NG_CS_1308111-1_SWITCHES_CORE_PROGRAM_CATALOG_0308-1234788.pdf")
    (property "symbolName1" "2454985-3")
)
